config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :time_periods
  resources :transactions do
		member do
			get 'success'
		end
  end
  resources :budgets
  resources :garins
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


		Rails.application.routes.draw do
  resources :time_periods
			devise_for :users, controllers: {
				registrations: 'users/registrations'
			}
		end
  # devise_for :users


  # root to: 'garins#index'
	root to: "garins#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/time_period.rb
class TimePeriod < ApplicationRecord
  belongs_to :garin
  has_many :budgets, dependent: :destroy


  def heb_month
    months = {
      1 => "ינואר",
      2 => "פברואר",
      3 => "מרץ",
      4 => "אפריל",
      5 => "מאי",
      6 => "יוני",
      7 => "יולי",
      8 => "אוגוסט",
      9 => "ספטמבר",
      10 => "אוקטובר",
      11 => "נובמבר",
      12 => "דצמבר"
    }
    months[self.date.month]
  end

  def transactions
    Transaction.where(budget_id: self.budgets.ids)
  end
end

app/controllers/time_periods_controller.rb
class TimePeriodsController < ApplicationController
  before_action :set_time_period, only: [:show, :edit, :update, :destroy]

  # GET /time_periods
  # GET /time_periods.json
  def index
    @time_periods = TimePeriod.all
  end

  # GET /time_periods/1
  # GET /time_periods/1.json
  def show
  end

  # GET /time_periods/new
  def new
    @time_period = TimePeriod.new
    @garin = current_user.garin
  end

  # GET /time_periods/1/edit
  def edit
    @garin = current_user.garin
  end

  # POST /time_periods
  # POST /time_periods.json
  def create
    @time_period = TimePeriod.new(time_period_params)
    @time_period.garin_id = params[:garin_id]
    if Garin.find(params[:garin_id]).time_periods.blank?
      @time_period.current_money = @time_period.money
    else
      @time_period.current_money = @time_period.money + TimePeriod.last.current_money
    end
    @time_period.money = @time_period.current_money
      if @time_period.save
        @time_period.garin.time_periods.last(2).first.budgets.each do |budget|
          new_budget = budget.dup
          new_budget.time_period = @time_period
          if new_budget.adding?
            new_budget.money = new_budget.current_money
          else
            new_budget.money = new_budget.money
            new_budget.current_money = new_budget.money
          end
          new_budget.save
        end
        redirect_to root_path, notice: 'מחזור כלכלי נוצר בהצלחה'
      else
        render :new
      end

  end

  # PATCH/PUT /time_periods/1
  # PATCH/PUT /time_periods/1.json
  def update
    @time_period.current_money = time_period_params[:money].to_i - (@time_period.money - @time_period.current_money)
    respond_to do |format|
      if @time_period.update(time_period_params)

        format.html { redirect_to root_path, notice: 'Time period was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_period }
      else
        format.html { render :edit }
        format.json { render json: @time_period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_periods/1
  # DELETE /time_periods/1.json
  def destroy
    @time_period.destroy
    respond_to do |format|
      format.html { redirect_to time_periods_url, notice: 'Time period was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_period
      @time_period = TimePeriod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_period_params
      params.require(:time_period).permit(:date, :length, :garin_id, :current_money, :money)
    end
end

app/helpers/time_periods_helper.rb
module TimePeriodsHelper
end

app/views/time_periods/_form.html.erb
<%= simple_form_for(@time_period) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date, as: :date, html5: true, input_html: {value: Date.today}, label: "תאריך התחלה" %>
    <% if @garin.time_periods.blank? %>
      <%= f.input :length, collection: 1...12, label: "אורך (בחודשים)" %>
    <% else %>
      <%= f.input :length, collection: 1...12, selected: TimePeriod.last.length, label: "אורך (בחודשים)" %>
    <% end %>
    <%= f.input :money, label: "סכום שנכנס"%>
    <%= hidden_field_tag(:garin_id, @garin.id) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "שליחה" %>
  </div>
<% end %>

app/views/time_periods/edit.html.erb
<h1>עריכת מחזור כלכלי</h1>

<%= render 'form', time_period: @time_period %>

<%= link_to 'Show', @time_period %> |
<%= link_to 'Back', time_periods_path %>

app/views/time_periods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Time Periods</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Length</th>
      <th>Garin</th>
      <th>Current money</th>
      <th>Money</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_periods.each do |time_period| %>
      <tr>
        <td><%= time_period.date %></td>
        <td><%= time_period.length %></td>
        <td><%= time_period.garin_id %></td>
        <td><%= time_period.current_money %></td>
        <td><%= time_period.money %></td>
        <td><%= link_to 'Show', time_period %></td>
        <td><%= link_to 'Edit', edit_time_period_path(time_period) %></td>
        <td><%= link_to 'Destroy', time_period, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time Period', new_time_period_path %>

app/views/time_periods/new.html.erb
<h1>מחזור כלכלי חדש</h1>

<%= render 'form', time_period: @time_period %>

app/views/time_periods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @time_period.date %>
</p>

<p>
  <strong>Length:</strong>
  <%= @time_period.length %>
</p>

<p>
  <strong>Garin:</strong>
  <%= @time_period.garin_id %>
</p>

<p>
  <strong>Current money:</strong>
  <%= @time_period.current_money %>
</p>

<p>
  <strong>Money:</strong>
  <%= @time_period.money %>
</p>

<%= link_to 'Edit', edit_time_period_path(@time_period) %> |
<%= link_to 'Back', time_periods_path %>