config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :time_periods
  resources :transactions do
		member do
			get 'success'
		end
  end
  resources :budgets
  resources :garins
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


		Rails.application.routes.draw do
  resources :time_periods
			devise_for :users, controllers: {
				registrations: 'users/registrations'
			}
		end
  # devise_for :users


  # root to: 'garins#index'
	root to: "garins#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/garin.rb
class Garin < ApplicationRecord
	validates :name, presence: true
	has_many :budgets, dependent: :destroy
	has_many :users
	has_many :time_periods, dependent: :destroy
	has_many :transactions, dependent: :destroy
	serialize :new_budgets, Array

	def new_money
		new_money = 0
		budgets.each do |budget|
			new_money += budget.money
	  end
		update(money: new_money)
	end

	def current_period
		self.time_periods.order(:id).last
	end

end

app/controllers/garins_controller.rb
class GarinsController < ApplicationController
 load_and_authorize_resource
  before_action :set_garin, only: [:show, :edit, :update, :destroy]

  # GET /garins
  # GET /garins.json
  def index
		unless current_user.admin?
			redirect_to root_path
		end
    @garins = Garin.all
  end

  # GET /garins/1
  # GET /garins/1.json
  def show
  end

  # GET /garins/new
  def new
    @garin = Garin.new
  end

  # GET /garins/1/edit
  def edit
  end

  # POST /garins
  # POST /garins.json
  def create
    @garin = Garin.new(garin_params)
		@garin.money = 0
		@garin.start_money = 0
    respond_to do |format|
      if @garin.save
        format.html { redirect_to @garin, notice: 'Garin was successfully created.' }
        format.json { render :show, status: :created, location: @garin }
      else
        format.html { render :new }
        format.json { render json: @garin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /garins/1
  # PATCH/PUT /garins/1.json
  def update
    respond_to do |format|
      if @garin.update(garin_params)
        format.html { redirect_to @garin, notice: 'Garin was successfully updated.' }
        format.json { render :show, status: :ok, location: @garin }
      else
        format.html { render :edit }
        format.json { render json: @garin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /garins/1
  # DELETE /garins/1.json
  def destroy
    @garin.destroy
    respond_to do |format|
      format.html { redirect_to garins_url, notice: 'Garin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garin
			if user_signed_in? && current_user.admin?
				@garin = Garin.find(params[:id])
			else
				@garin = current_user.garin
			end
    end

    # Only allow a list of trusted parameters through.
    def garin_params
      params.require(:garin).permit(:name, :money, :start_money, :start_day, budgets_ids:[])
    end
end

app/helpers/garins_helper.rb
module GarinsHelper
end

app/views/garins/_budget.html.slim
= f.input :new_budgets, as: :text, multiple: true

app/views/garins/_form.html.erb
<%= simple_form_for @garin do |f| %>
	<%= f.input :name, label: "שם" %>
	<%= f.input :start_money , label: "כסף התחלתי" if action_name == "new" %>
	<%= f.input :start_day, collection: [10, 12, 15], label: "יום תחילת מחזור כלכלי" %>
	<%= f.button :submit, "שליחה" %>
<% end %>

app/views/garins/edit.html.erb
<h1>עריכת גרעין</h1>

<%= render 'form', garin: @garin %>

app/views/garins/index.html.slim
p#notice
  = notice
h1
  | Garins
table
  thead
    tr
      th
        | Name
      th
        | Money
      th
        | Budget
      th[colspan="3"]
  tbody
    - @garins.each do |garin|
      tr
        td
          = garin.name
        td
          = garin.money
        td
          = garin.budgets.pluck(:name)
        td
          = link_to 'Show', garin
        td
          = link_to 'Edit', edit_garin_path(garin)
        td
          = link_to 'Destroy', garin, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Garin', new_garin_path

app/views/garins/new.html.erb
<h1>עריכת גרעין</h1>

<%= render 'form', garin: @garin %>

app/views/garins/show.html.erb
  <div class="garin-budgets">
    <% if @garin.time_periods.blank? %>
      <%= link_to 'התחלת מחזור כלכלי חדש', new_time_period_path, class: "block p-5 lg:inline-block text-xl lg:mt-0 lg:mr-4 mb-2 lg:mb-0 " %>
    <% elsif @garin.current_period.budgets.empty? %>
      <%= link_to 'קופה חדשה', new_budget_path, class: "block p-5 lg:inline-block text-xl lg:mt-0 lg:mr-4 mb-2 lg:mb-0 " %>
    <% else %>
      <% @garin.current_period.budgets.sort.each do |budget| %>
        <%= link_to budget, class:"garin-show-budget" do %>
        <% if budget.current_money <= 0 %>
          <div class="red">
        <% elsif budget.current_money <= budget.money * 0.1 %>
          <div class="orange">
        <% else %>
          <div class="original">
        <% end %>
            <h1>
              <%= budget.name %>
            </h1>
            <span>
              <% if budget.totaled? %>
                <%= strip_trailing_zero(budget.money) %>/
              <% end %>
            </span>
            <span>
              <%= strip_trailing_zero(budget.current_money) %>
            </span>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>