config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :time_periods
  resources :transactions do
		member do
			get 'success'
		end
  end
  resources :budgets
  resources :garins
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


		Rails.application.routes.draw do
  resources :time_periods
			devise_for :users, controllers: {
				registrations: 'users/registrations'
			}
		end
  # devise_for :users


  # root to: 'garins#index'
	root to: "garins#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <% if current_page?(root_url) %>
    <header class="root flex justify-between" >
      <div class="content flex flex-col justify-between p-3">
        <div class="text-2xl">
          <%= link_to "כלכלת #{current_user.garin.name}", root_path, class:"title" if user_signed_in? %>
        </div>
        <% if current_user.garin.time_periods.present? %>
          <div class="text-xl">
            <%= current_user.garin.current_period.heb_month %>     <%= link_to "<i class='material-icons'>edit</i>".html_safe, edit_time_period_path(current_user.garin.current_period) %>
          </div>
          <div class="">
            <span class="text-2xl"><%= strip_trailing_zero(current_user.garin.current_period.money) %>/</span>
            <span class="font-bold text-3xl"><%= strip_trailing_zero(current_user.garin.current_period.current_money) %></span>
          </div>
        <% end %>

      </div>
    </header>
  <% else %>
  <header class="flex justify-between" >
    <div class="content flex items-center p-3 justify-between">
      <div class="text-2xl">
        <%= link_to "כלכלת #{current_user.garin.name}", root_path, class:"title" if user_signed_in? %>
      </div>
    </div>
  </header>
  <% end %>
<% end %>
<nav>
  <%= link_to "<i class='material-icons text-white text-5xl'>add</i>".html_safe, new_transaction_path if user_signed_in? %>
  <div class="hamburger block">
    <button class="flex items-center" type="button" name="button">
      <i class='material-icons text-white text-5xl'>menu</i>
    </button>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<aside class="">
  <%  if user_signed_in? %>
    <%= link_to "גרעינים", garins_path, class: "block p-5 lg:inline-block text-xl lg:mt-0 lg:mr-4 mb-2 lg:mb-0 " if current_user.admin? %>
    <%= link_to "הוצאות", transactions_path, class: "block p-5 lg:inline-block text-xl lg:mt-0 lg:mr-4 mb-2 lg:mb-0 " %>
    <%= link_to 'התחלת מחזור כלכלי חדש', new_time_period_path, class: "block p-5 lg:inline-block text-xl lg:mt-0 lg:mr-4 mb-2 lg:mb-0 ", data: {confirm: "בטוחים.ות?"} %>
    <%= link_to 'קופה חדשה', new_budget_path, class: "block p-5 lg:inline-block text-xl lg:mt-0 lg:mr-4 mb-2 lg:mb-0 " %>
    <a href="whatsapp://send?text=<%= root_url %>users/sign_up?g=<%= current_user.garin.id %>" class="block p-5 lg:inline-block text-xl lg:mt-0 lg:mr-4 mb-2 lg:mb-0 ">קישור הצטרפות לגרעין</a>
    <%= link_to 'עריכת הגרעין', edit_garin_path(current_user.garin), class: "block p-5 lg:inline-block text-xl lg:mt-0 lg:mr-4 mb-2 lg:mb-0 " if user_signed_in? %>
    <%= link_to 'עריכת המשתמש',  edit_user_registration_path , class: "block p-5 lg:inline-block text-xl lg:mt-0 lg:mr-4 mb-2 lg:mb-0 " if user_signed_in? %>
    <%= link_to "התנתקות", destroy_user_session_path, method: :delete, class:"block p-5 lg:inline-block text-xl lg:mt-0 lg:mr-4 mb-2 lg:mb-0 "  if user_signed_in? %>
  <% end %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="he" dir="rtl">
  <head>
    <meta content=("text/html; charset=UTF-8") http-equiv="Content-Type">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.22/r-2.2.6/sp-1.2.0/datatables.min.css">
		<title> תקציב גרעין</title>
    <meta property="og:title" content="כלכלה גרעינית">
    <meta property="og:description" content="אפליקציית ניהול כלכלי לגרעיני תנועת השומר הצעיר">
    <meta property="og:type" content="website">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<meta content="width=device-width, initial-scale=1" name="viewport" />
		<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload'%>
		<%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload'%>
		<%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload'%>
    <title></title>
  </head>
  <body class="bg-white">
    <% flash.each do |type, message| %>
      <% if type == "alert" %>
        <div class="bg-red-500 fixed bottom-0 w-full">
          <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %><div>
        </div>
      <% end %>
      <% if type == "notice" %>
        <div class="bg-green-500 fixed bottom-0 w-full">
          <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
        </div>
      <% end %>
    <% end %>
    <% if user_signed_in? %>
      <%= render partial: "layouts/header" %>
      <%= render partial: "layouts/sidebar" %>
    <% end %>
    <% if current_page?(root_url) %>
      <main class="lg:px-10 px-4 root">
        <%= content_for?(:content) ? yield(:content) : yield %>
      </main>
    <% else %>
      <main class="lg:px-10 px-4">
        <%= content_for?(:content) ? yield(:content) : yield %>
      </main>
    <% end %>
  </body>
</html>



<script>
	$(document).ready(function() {
		$(".hamburger").click(function(event) {
			$("aside").toggleClass("open")
      $(":not(aside):not(.hamburger):not(html):not(body):not(aside *):not(.hamburger *):not(nav)").toggleClass("pointer-none")
      $("body").toggleClass("overflow-hidden")
		});
    $('#table').DataTable({
      responsive: true,
      processing: true,
			pageLength: 25,
      paging: true,
      fixedHeader: true,
			ajax: {
				"url": $('#table').data('source')
			},
      language: {
        "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Hebrew.json"
      },
    });
	});
</script>